# Generated by Django 5.0.6 on 2024-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
